# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef1274fed758620f4ad902ba33fc80d3a7d3d2b1dbd3bd72e9d89297de8681583c09b21fe1da02209bad26bba796b8388455bd3c1194f7aae7b6b0b102b8d637

test:
  secret_key_base: 85ab06c5fc935f7fc7b4ca851d5ec98f34277c4b6a2bf7a0babce593f0f4e74834359cc33195cdc6b28e9a0af673232a8e07e8e161d4fc55a70cb90af4757683

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
